package model;

import java.util.Date;
import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Artista {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long Id;
	
	private String Nome;
	private Date DataNascita,DataMorte;
	@OneToMany
	private Map<Long , Opera> opereRealizzate;	//long refer to the AutoGeneratedValue
	
	public Artista(String nome, Date dataNascita){
		this.Nome=nome;
		this.DataNascita=dataNascita;
	}
	public Artista(String nome, Date dataNascita, Date dataMorte){
		this.Nome=nome;
		this.DataNascita=dataNascita;
		this.DataMorte=dataMorte;
	}
	
	public void addOpera(Opera opera){
		this.opereRealizzate.put(opera.getId(), opera);
	}
	
	public Long getId() {
		return Id;
	}
	public void setId(Long id) {
		Id = id;
	}
	public String getNome() {
		return Nome;
	}
	public void setNome(String nome) {
		Nome = nome;
	}
	public Date getDataNascita() {
		return DataNascita;
	}
	public void setDataNascita(Date dataNascita) {
		DataNascita = dataNascita;
	}
	public Date getDataMorte() {
		return DataMorte;
	}
	public void setDataMorte(Date dataMorte) {
		DataMorte = dataMorte;
	}
	public Map<Long, Opera> getOpereRealizzate() {
		return opereRealizzate;
	}
	public void setOpereRealizzate(Map<Long, Opera> opereRealizzate) {
		this.opereRealizzate = opereRealizzate;
	}
	
	
	
}
